# # PHP CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-php/ for more details
# #
version: 2
jobs:
  build:
    machine:
      enabled: true

    timezone:
      Europe/Amsterdam
    node:
      version: 6.0.0
    python:
      version: 2.7.10
    
    branches:
      only:
        - master

    steps:
        - run:
            name: "Install Gulp"
            command: npm install gulp -g
        - run:
            name: "Install Bower"
            command: npm install bower -g
        - run:
            name: "Install Ansible"
            command: pip install ansible
        - checkout
        - deploy:
            command: cd ../../project/trellis && ansible-playbook deploy.yml -e "site=webbio-staging.nl env=staging" -i hosts/staging --skip-tags "skip-using-ci" -vvv