# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: productionpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  webbio.nl:
    env:
      db_password: 2dY2EOF*#Ama
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "yzB!%z`P]s+NcPu+t:-gyZY6q+j}JvL$B%3UGzVt<,sRos=1[#ivEZU#|;CxW(YP"
      secure_auth_key: "|aKvMSZ#4,V%W-,d4qwIBOPNT=C6ioz5]BL!5}B2RG-<0hFB$z#$oHyrtK7vW&`u"
      logged_in_key: "EH8/,6SvrxN=jSA5u{T,sMb^@o|Ftsv;>O3Th}:]</R@?^[wQ%FZ|o?$kZ.XK[dW"
      nonce_key: "U;7/uap-#&`rNC]&VLEW7qmSnqrQ)DDLS0=fOa3xLA3sO?*-0-;?<4@{$)tu?=v7"
      auth_salt: "./e<DVUy9&9Q^:Z>g_EVBH2jfsir^_lwVLL=s_`=iR]8mD`=F:}eF%*^1UW0Csk3"
      secure_auth_salt: "%).7cU&WRqdipQL>@BvNVNx==H5$u92{aN9Ohd?W1h!Gc(yC_$=q7M*Gs{kHDvG%"
      logged_in_salt: "ibj+0/:,2q5ae[jG.7DI,6CFg.b4>_?z77[-a!Ln.lN&GnzP.rB8/ExG),,7]Eh>"
      nonce_salt: "]=:lp@Qf5F_xOpLay,#7P?5-,WuK/XxUueZU@sHGc#Xk1.)Nvag!ktkXESznr!]H"
